web:
    image: shaneburkhart/branded_spinner
    ports:
        - "3000:3000"
    links:
        - pg
        - redis
    volumes:
        - .:/app
    env_file:
        - user.env
    command: "node_modules/nodemon/bin/nodemon.js ./index.js 127.0.0.1 3000"

pg:
    image: postgres:10.3
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=mydb
    volumes:
        - ./data/pg:/var/lib/postgresql/data

redis:
    image: redis:3.2
